//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_likes
    {
        public string UserId { get; set; }
        public int BlogId { get; set; }
        public string LikerId { get; set; }
        public Nullable<System.DateTime> LikeDateTime { get; set; }
    
        public virtual blog blog { get; set; }
    }
}
