//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationEntities : DbContext
    {
        public RegistrationEntities()
            : base("name=RegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<registration> registrations { get; set; }
    
        public virtual ObjectResult<user_login_Result> user_login(string id, string password)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user_login_Result>("user_login", idParameter, passwordParameter);
        }
    
        public virtual int user_signup(string user_id, string first_name, string middle_name, string last_name, string phone_number, string email_id, string gender, Nullable<System.DateTime> date_of_birth, string pass, string photo_filename, string bio)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var date_of_birthParameter = date_of_birth.HasValue ?
                new ObjectParameter("date_of_birth", date_of_birth) :
                new ObjectParameter("date_of_birth", typeof(System.DateTime));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var photo_filenameParameter = photo_filename != null ?
                new ObjectParameter("photo_filename", photo_filename) :
                new ObjectParameter("photo_filename", typeof(string));
    
            var bioParameter = bio != null ?
                new ObjectParameter("bio", bio) :
                new ObjectParameter("bio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("user_signup", user_idParameter, first_nameParameter, middle_nameParameter, last_nameParameter, phone_numberParameter, email_idParameter, genderParameter, date_of_birthParameter, passParameter, photo_filenameParameter, bioParameter);
        }
    
        public virtual int update_profile(string uidold, string uidnew, string fname, string mname, string lname, string pnumber, string eid, string password, string photo, string bio)
        {
            var uidoldParameter = uidold != null ?
                new ObjectParameter("uidold", uidold) :
                new ObjectParameter("uidold", typeof(string));
    
            var uidnewParameter = uidnew != null ?
                new ObjectParameter("uidnew", uidnew) :
                new ObjectParameter("uidnew", typeof(string));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var mnameParameter = mname != null ?
                new ObjectParameter("mname", mname) :
                new ObjectParameter("mname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var pnumberParameter = pnumber != null ?
                new ObjectParameter("pnumber", pnumber) :
                new ObjectParameter("pnumber", typeof(string));
    
            var eidParameter = eid != null ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var bioParameter = bio != null ?
                new ObjectParameter("bio", bio) :
                new ObjectParameter("bio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_profile", uidoldParameter, uidnewParameter, fnameParameter, mnameParameter, lnameParameter, pnumberParameter, eidParameter, passwordParameter, photoParameter, bioParameter);
        }
    }
}
