//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationEntities6 : DbContext
    {
        public RegistrationEntities6()
            : base("name=RegistrationEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<follower> followers { get; set; }
    
        public virtual int delete_follower(string uid, string fid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var fidParameter = fid != null ?
                new ObjectParameter("fid", fid) :
                new ObjectParameter("fid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_follower", uidParameter, fidParameter);
        }
    
        public virtual ObjectResult<get_followers_Result> get_followers(string uid, string fid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var fidParameter = fid != null ?
                new ObjectParameter("fid", fid) :
                new ObjectParameter("fid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_followers_Result>("get_followers", uidParameter, fidParameter);
        }
    }
}
