//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationEntities3 : DbContext
    {
        public RegistrationEntities3()
            : base("name=RegistrationEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blog_likes> blog_likes { get; set; }
    
        public virtual int blog_like_insert(string uid, Nullable<int> bid, string lid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var lidParameter = lid != null ?
                new ObjectParameter("lid", lid) :
                new ObjectParameter("lid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("blog_like_insert", uidParameter, bidParameter, lidParameter);
        }
    
        public virtual int like_count(string uid, Nullable<int> bid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("like_count", uidParameter, bidParameter);
        }
    
        public virtual int dislike(string uid, Nullable<int> bid, string lid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var lidParameter = lid != null ?
                new ObjectParameter("lid", lid) :
                new ObjectParameter("lid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dislike", uidParameter, bidParameter, lidParameter);
        }
    }
}
