//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationEntities2 : DbContext
    {
        public RegistrationEntities2()
            : base("name=RegistrationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<blog_likes> blog_likes { get; set; }
    
        public virtual int inc_likes(string id, Nullable<int> bid)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inc_likes", idParameter, bidParameter);
        }
    
        public virtual ObjectResult<user_titles_Result> user_titles(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user_titles_Result>("user_titles", uidParameter);
        }
    
        public virtual int delete_blog(string uid, Nullable<int> bid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_blog", uidParameter, bidParameter);
        }
    
        public virtual ObjectResult<get_blog_for_update_Result> get_blog_for_update(string uid, Nullable<int> bid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_blog_for_update_Result>("get_blog_for_update", uidParameter, bidParameter);
        }
    
        public virtual int update_blog(string uid, Nullable<int> bid, string btitle, string bimage, string bcontent, string btype)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var btitleParameter = btitle != null ?
                new ObjectParameter("btitle", btitle) :
                new ObjectParameter("btitle", typeof(string));
    
            var bimageParameter = bimage != null ?
                new ObjectParameter("bimage", bimage) :
                new ObjectParameter("bimage", typeof(string));
    
            var bcontentParameter = bcontent != null ?
                new ObjectParameter("bcontent", bcontent) :
                new ObjectParameter("bcontent", typeof(string));
    
            var btypeParameter = btype != null ?
                new ObjectParameter("btype", btype) :
                new ObjectParameter("btype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_blog", uidParameter, bidParameter, btitleParameter, bimageParameter, bcontentParameter, btypeParameter);
        }
    
        public virtual int blog_like_insert(string uid, Nullable<int> bid, string lid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var lidParameter = lid != null ?
                new ObjectParameter("lid", lid) :
                new ObjectParameter("lid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("blog_like_insert", uidParameter, bidParameter, lidParameter);
        }
    
        public virtual int like_count(string uid, Nullable<int> bid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("like_count", uidParameter, bidParameter);
        }
    
        public virtual int blog_insert(string uid, string title, string img, string content, string type)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("blog_insert", uidParameter, titleParameter, imgParameter, contentParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> blog_count(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("blog_count", uidParameter);
        }
    
        public virtual ObjectResult<get_blogs_Result1> get_blogs(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_blogs_Result1>("get_blogs", uidParameter);
        }
    
        public virtual ObjectResult<get_user_blogs_Result> get_user_blogs(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_user_blogs_Result>("get_user_blogs", uidParameter);
        }
    }
}
