//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public string user_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string phone_number { get; set; }
        public string email_id { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string pass { get; set; }
        public string photo_filename { get; set; }
        public string bio { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string user_role { get; set; }
    }
}
